Repository fond-of-oryx/fond-of-oryx, pull requests merged in 2023-03, with the labels that each got.

#229 :sparkles: adds erp delivery note tracking code functionality
  bundles/erp-delivery-note-api/tests/FondOfOryx/Zed/ErpDeliveryNoteApi/Dependency/Facade/ErpDeliveryNoteApiToApiFacadeBridgeTest.php
  bundles/erp-delivery-note-extension/src/FondOfOryx/Zed/ErpDeliveryNoteExtension/Dependency/Plugin/ErpDeliveryNoteTrackingPostSavePluginInterface.php
  bundles/erp-delivery-note-extension/src/FondOfOryx/Zed/ErpDeliveryNoteExtension/Dependency/Plugin/ErpDeliveryNoteTrackingPreSavePluginInterface.php
  bundles/erp-delivery-note-page-search-rest-api/src/FondOfOryx/Glue/ErpDeliveryNotePageSearchRestApi/Model/Mapper/RestErpDeliveryNotePageSearchCollectionResponseMapper.php
  bundles/erp-delivery-note-page-search-rest-api/src/FondOfOryx/Shared/ErpDeliveryNotePageSearchRestApi/Transfer/erp_delivery_note_page_search_rest_api.transfer.xml
  bundles/erp-delivery-note-page-search/src/FondOfOryx/Zed/ErpDeliveryNotePageSearch/Business/Mapper/ErpDeliveryNotePageSearchDataMapper.php
  bundles/erp-delivery-note-page-search/src/FondOfOryx/Zed/ErpDeliveryNotePageSearch/Business/Publisher/ErpDeliveryNotePageSearchPublisher.php
  bundles/erp-delivery-note-page-search/tests/FondOfOryx/Zed/ErpDeliveryNotePageSearch/Business/Publisher/ErpDeliveryNotePageSearchPublisherTest.php
  bundles/erp-delivery-note/src/FondOfOryx/Shared/ErpDeliveryNote/Transfer/erp_delivery_note.transfer.xml
  bundles/erp-delivery-note/src/FondOfOryx/Zed/ErpDeliveryNote/Business/ErpDeliveryNoteBusinessFactory.php
  bundles/erp-delivery-note/src/FondOfOryx/Zed/ErpDeliveryNote/Business/ErpDeliveryNoteFacade.php
  bundles/erp-delivery-note/src/FondOfOryx/Zed/ErpDeliveryNote/Business/ErpDeliveryNoteFacadeInterface.php
  bundles/erp-delivery-note/src/FondOfOryx/Zed/ErpDeliveryNote/Business/Handler/ErpDeliveryNoteItemHandler.php
  bundles/erp-delivery-note/src/FondOfOryx/Zed/ErpDeliveryNote/Business/Handler/ErpDeliveryNoteTrackingHandler.php
  bundles/erp-delivery-note/src/FondOfOryx/Zed/ErpDeliveryNote/Business/Handler/ErpDeliveryNoteTrackingHandlerInterface.php
  bundles/erp-delivery-note/src/FondOfOryx/Zed/ErpDeliveryNote/Business/Model/Reader/ErpDeliveryNoteTrackingReader.php
  bundles/erp-delivery-note/src/FondOfOryx/Zed/ErpDeliveryNote/Business/Model/Reader/ErpDeliveryNoteTrackingReaderInterface.php
  bundles/erp-delivery-note/src/FondOfOryx/Zed/ErpDeliveryNote/Business/Model/Writer/ErpDeliveryNoteTrackingWriter.php
  bundles/erp-delivery-note/src/FondOfOryx/Zed/ErpDeliveryNote/Business/Model/Writer/ErpDeliveryNoteTrackingWriterInterface.php
  bundles/erp-delivery-note/src/FondOfOryx/Zed/ErpDeliveryNote/Business/PluginExecutor/ErpDeliveryNoteTrackingPluginExecutor.php
  bundles/erp-delivery-note/src/FondOfOryx/Zed/ErpDeliveryNote/Business/PluginExecutor/ErpDeliveryNoteTrackingPluginExecutorInterface.php
  bundles/erp-delivery-note/src/FondOfOryx/Zed/ErpDeliveryNote/Communication/Plugin/PostSave/ErpDeliveryNoteTrackingDataPersisterErpDeliveryNotePostSavePlugin.php
  bundles/erp-delivery-note/src/FondOfOryx/Zed/ErpDeliveryNote/ErpDeliveryNoteDependencyProvider.php
  bundles/erp-delivery-note/src/FondOfOryx/Zed/ErpDeliveryNote/Persistence/ErpDeliveryNoteEntityManager.php
  bundles/erp-delivery-note/src/FondOfOryx/Zed/ErpDeliveryNote/Persistence/ErpDeliveryNoteEntityManagerInterface.php
  bundles/erp-delivery-note/src/FondOfOryx/Zed/ErpDeliveryNote/Persistence/ErpDeliveryNotePersistenceFactory.php
  bundles/erp-delivery-note/src/FondOfOryx/Zed/ErpDeliveryNote/Persistence/ErpDeliveryNoteRepository.php
  bundles/erp-delivery-note/src/FondOfOryx/Zed/ErpDeliveryNote/Persistence/ErpDeliveryNoteRepositoryInterface.php
  bundles/erp-delivery-note/src/FondOfOryx/Zed/ErpDeliveryNote/Persistence/Propel/Mapper/EntityToTransferMapper.php
  bundles/erp-delivery-note/src/FondOfOryx/Zed/ErpDeliveryNote/Persistence/Propel/Mapper/EntityToTransferMapperInterface.php
  bundles/erp-delivery-note/src/FondOfOryx/Zed/ErpDeliveryNote/Persistence/Propel/Schema/erp_delivery_note.schema.xml
  bundles/erp-delivery-note/tests/FondOfOryx/Zed/ErpDeliveryNote/Business/Handler/ErpDeliveryNoteItemHandlerTest.php
  bundles/erp-delivery-note/tests/FondOfOryx/Zed/ErpDeliveryNote/Business/Handler/ErpDeliveryNoteTrackingHandlerTest.php
  bundles/erp-delivery-note/tests/FondOfOryx/Zed/ErpDeliveryNote/Business/Model/Reader/ErpDeliveryNoteTrackingReaderTest.php
  bundles/erp-delivery-note/tests/FondOfOryx/Zed/ErpDeliveryNote/Business/Model/Writer/ErpDeliveryNoteTrackingWriterTest.php
  bundles/erp-delivery-note/tests/FondOfOryx/Zed/ErpDeliveryNote/Business/PluginExecutor/ErpDeliveryNoteTrackingPluginExecutorTest.php
  dandelion.json
Labels: enhancement

#232 fix dependencies for erp delivery note packages
  bundles/erp-delivery-note-api/composer.json
  bundles/erp-delivery-note-page-search-rest-api/composer.json
  bundles/erp-delivery-note-page-search/composer.json
  dandelion.json
Labels: dependencies

#234 Erp invoice delivery note fix
  bundles/erp-delivery-note/src/FondOfOryx/Zed/ErpDeliveryNote/Persistence/ErpDeliveryNoteEntityManager.php
  bundles/erp-invoice/src/FondOfOryx/Zed/ErpInvoice/Persistence/ErpInvoiceEntityManager.php
  dandelion.json
Labels: bug

#237 Delivery note global tracking data
  bundles/erp-delivery-note-page-search-rest-api/src/FondOfOryx/Glue/ErpDeliveryNotePageSearchRestApi/Model/Mapper/RestErpDeliveryNotePageSearchCollectionResponseMapper.php
  bundles/erp-delivery-note-page-search-rest-api/src/FondOfOryx/Shared/ErpDeliveryNotePageSearchRestApi/Transfer/erp_delivery_note_page_search_rest_api.transfer.xml
  bundles/erp-delivery-note-page-search-rest-api/tests/FondOfOryx/Glue/ErpDeliveryNotePageSearchRestApi/Model/Mapper/RestErpDeliveryNotePageSearchCollectionResponseMapperTest.php
  dandelion.json
Labels: enhancement

#247 :package: add CompanyDeleterProductListConnector bundle
  bundles/company-deleter-product-list-connector/.github/workflows/main.yml
  bundles/company-deleter-product-list-connector/.gitignore
  bundles/company-deleter-product-list-connector/LICENSE
  bundles/company-deleter-product-list-connector/Makefile
  bundles/company-deleter-product-list-connector/README.md
  bundles/company-deleter-product-list-connector/codeception.yml
  bundles/company-deleter-product-list-connector/composer.json
  bundles/company-deleter-product-list-connector/phpstan.neon
  bundles/company-deleter-product-list-connector/src/FondOfOryx/Zed/CompanyDeleterProductListConnector/Business/CompanyDeleterProductListConnectorBusinessFactory.php
  bundles/company-deleter-product-list-connector/src/FondOfOryx/Zed/CompanyDeleterProductListConnector/Business/CompanyDeleterProductListConnectorFacade.php
  bundles/company-deleter-product-list-connector/src/FondOfOryx/Zed/CompanyDeleterProductListConnector/Business/CompanyDeleterProductListConnectorFacadeInterface.php
  bundles/company-deleter-product-list-connector/src/FondOfOryx/Zed/CompanyDeleterProductListConnector/Business/Model/CompanyToProductListDeleter.php
  bundles/company-deleter-product-list-connector/src/FondOfOryx/Zed/CompanyDeleterProductListConnector/Business/Model/CompanyToProductListDeleterInterface.php
  bundles/company-deleter-product-list-connector/src/FondOfOryx/Zed/CompanyDeleterProductListConnector/Communication/Plugin/CompanyToProductListDeleterPrePlugin.php
  bundles/company-deleter-product-list-connector/src/FondOfOryx/Zed/CompanyDeleterProductListConnector/Persistence/CompanyDeleterProductListConnectorEntityManager.php
  bundles/company-deleter-product-list-connector/src/FondOfOryx/Zed/CompanyDeleterProductListConnector/Persistence/CompanyDeleterProductListConnectorEntityManagerInterface.php
  bundles/company-deleter-product-list-connector/src/FondOfOryx/Zed/CompanyDeleterProductListConnector/Persistence/CompanyDeleterProductListConnectorPersistenceFactory.php
  bundles/company-deleter-product-list-connector/tests/FondOfOryx/.gitkeep
  bundles/company-deleter-product-list-connector/tests/_bootstrap.php
  bundles/company-deleter-product-list-connector/tests/_data/.gitkeep
  bundles/company-deleter-product-list-connector/tests/_output/.gitignore
  bundles/company-deleter-product-list-connector/tests/_support/.gitkeep
Labels: enhancement

#251 Company deleter erp order connector
  bundles/company-deleter-erp-order-connector/.github/workflows/main.yml
  bundles/company-deleter-erp-order-connector/.gitignore
  bundles/company-deleter-erp-order-connector/LICENSE
  bundles/company-deleter-erp-order-connector/Makefile
  bundles/company-deleter-erp-order-connector/README.md
  bundles/company-deleter-erp-order-connector/codeception.yml
  bundles/company-deleter-erp-order-connector/composer.json
  bundles/company-deleter-erp-order-connector/phpstan.neon
  bundles/company-deleter-erp-order-connector/src/FondOfOryx/Zed/CompanyDeleterErpOrderConnector/Business/CompanyDeleterErpOrderConnectorBusinessFactory.php
  bundles/company-deleter-erp-order-connector/src/FondOfOryx/Zed/CompanyDeleterErpOrderConnector/Business/CompanyDeleterErpOrderConnectorFacade.php
  bundles/company-deleter-erp-order-connector/src/FondOfOryx/Zed/CompanyDeleterErpOrderConnector/Business/CompanyDeleterErpOrderConnectorFacadeInterface.php
  bundles/company-deleter-erp-order-connector/src/FondOfOryx/Zed/CompanyDeleterErpOrderConnector/Business/Model/ErpOrderDeleter.php
  bundles/company-deleter-erp-order-connector/src/FondOfOryx/Zed/CompanyDeleterErpOrderConnector/Business/Model/ErpOrderDeleterInterface.php
  bundles/company-deleter-erp-order-connector/src/FondOfOryx/Zed/CompanyDeleterErpOrderConnector/Communication/Plugin/ErpOrderDeleterPrePlugin.php
  bundles/company-deleter-erp-order-connector/src/FondOfOryx/Zed/CompanyDeleterErpOrderConnector/Persistence/CompanyDeleterErpOrderConnectorEntityManager.php
  bundles/company-deleter-erp-order-connector/src/FondOfOryx/Zed/CompanyDeleterErpOrderConnector/Persistence/CompanyDeleterErpOrderConnectorEntityManagerInterface.php
  bundles/company-deleter-erp-order-connector/src/FondOfOryx/Zed/CompanyDeleterErpOrderConnector/Persistence/CompanyDeleterErpOrderConnectorPersistenceFactory.php
  bundles/company-deleter-erp-order-connector/tests/FondOfOryx/.gitkeep
  bundles/company-deleter-erp-order-connector/tests/_bootstrap.php
  bundles/company-deleter-erp-order-connector/tests/_data/.gitkeep
  bundles/company-deleter-erp-order-connector/tests/_output/.gitignore
  bundles/company-deleter-erp-order-connector/tests/_support/.gitkeep
Labels: enhancement

#250 Company deleter erp invoice connector
  bundles/company-deleter-erp-invoice-connector/.github/workflows/main.yml
  bundles/company-deleter-erp-invoice-connector/.gitignore
  bundles/company-deleter-erp-invoice-connector/LICENSE
  bundles/company-deleter-erp-invoice-connector/Makefile
  bundles/company-deleter-erp-invoice-connector/README.md
  bundles/company-deleter-erp-invoice-connector/codeception.yml
  bundles/company-deleter-erp-invoice-connector/composer.json
  bundles/company-deleter-erp-invoice-connector/phpstan.neon
  bundles/company-deleter-erp-invoice-connector/src/FondOfOryx/Zed/CompanyDeleterErpInvoiceConnector/Business/CompanyDeleterErpInvoiceConnectorBusinessFactory.php
  bundles/company-deleter-erp-invoice-connector/src/FondOfOryx/Zed/CompanyDeleterErpInvoiceConnector/Business/CompanyDeleterErpInvoiceConnectorFacade.php
  bundles/company-deleter-erp-invoice-connector/src/FondOfOryx/Zed/CompanyDeleterErpInvoiceConnector/Business/CompanyDeleterErpInvoiceConnectorFacadeInterface.php
  bundles/company-deleter-erp-invoice-connector/src/FondOfOryx/Zed/CompanyDeleterErpInvoiceConnector/Business/Model/ErpInvoiceDeleter.php
  bundles/company-deleter-erp-invoice-connector/src/FondOfOryx/Zed/CompanyDeleterErpInvoiceConnector/Business/Model/ErpInvoiceDeleterInterface.php
  bundles/company-deleter-erp-invoice-connector/src/FondOfOryx/Zed/CompanyDeleterErpInvoiceConnector/Communication/Plugin/ErpInvoiceDeleterPrePlugin.php
  bundles/company-deleter-erp-invoice-connector/src/FondOfOryx/Zed/CompanyDeleterErpInvoiceConnector/Persistence/CompanyDeleterErpInvoiceConnectorEntityManager.php
  bundles/company-deleter-erp-invoice-connector/src/FondOfOryx/Zed/CompanyDeleterErpInvoiceConnector/Persistence/CompanyDeleterErpInvoiceConnectorEntityManagerInterface.php
  bundles/company-deleter-erp-invoice-connector/src/FondOfOryx/Zed/CompanyDeleterErpInvoiceConnector/Persistence/CompanyDeleterErpInvoiceConnectorPersistenceFactory.php
  bundles/company-deleter-erp-invoice-connector/tests/FondOfOryx/.gitkeep
  bundles/company-deleter-erp-invoice-connector/tests/_bootstrap.php
  bundles/company-deleter-erp-invoice-connector/tests/_data/.gitkeep
  bundles/company-deleter-erp-invoice-connector/tests/_output/.gitignore
  bundles/company-deleter-erp-invoice-connector/tests/_support/.gitkeep
Labels: enhancement

#248 :package: add CompanyDeleterCompanyBusinessUnitConnector bundle
  bundles/company-deleter-company-business-unit-connector/.github/workflows/main.yml
  bundles/company-deleter-company-business-unit-connector/.gitignore
  bundles/company-deleter-company-business-unit-connector/LICENSE
  bundles/company-deleter-company-business-unit-connector/Makefile
  bundles/company-deleter-company-business-unit-connector/README.md
  bundles/company-deleter-company-business-unit-connector/codeception.yml
  bundles/company-deleter-company-business-unit-connector/composer.json
  bundles/company-deleter-company-business-unit-connector/phpstan.neon
  bundles/company-deleter-company-business-unit-connector/src/FondOfOryx/Zed/CompanyDeleterCompanyBusinessUnitConnector/Business/CompanyDeleterCompanyBusinessUnitConnectorBusinessFactory.php
  bundles/company-deleter-company-business-unit-connector/src/FondOfOryx/Zed/CompanyDeleterCompanyBusinessUnitConnector/Business/CompanyDeleterCompanyBusinessUnitConnectorFacade.php
  bundles/company-deleter-company-business-unit-connector/src/FondOfOryx/Zed/CompanyDeleterCompanyBusinessUnitConnector/Business/CompanyDeleterCompanyBusinessUnitConnectorFacadeInterface.php
  bundles/company-deleter-company-business-unit-connector/src/FondOfOryx/Zed/CompanyDeleterCompanyBusinessUnitConnector/Business/Model/BusinessUnitDeleter.php
  bundles/company-deleter-company-business-unit-connector/src/FondOfOryx/Zed/CompanyDeleterCompanyBusinessUnitConnector/Business/Model/BusinessUnitDeleterInterface.php
  bundles/company-deleter-company-business-unit-connector/src/FondOfOryx/Zed/CompanyDeleterCompanyBusinessUnitConnector/Communication/Plugin/CompanyBusinessUnitDeleterPrePlugin.php
  bundles/company-deleter-company-business-unit-connector/src/FondOfOryx/Zed/CompanyDeleterCompanyBusinessUnitConnector/Persistence/CompanyDeleterCompanyBusinessUnitConnectorEntityManager.php
  bundles/company-deleter-company-business-unit-connector/src/FondOfOryx/Zed/CompanyDeleterCompanyBusinessUnitConnector/Persistence/CompanyDeleterCompanyBusinessUnitConnectorEntityManagerInterface.php
  bundles/company-deleter-company-business-unit-connector/src/FondOfOryx/Zed/CompanyDeleterCompanyBusinessUnitConnector/Persistence/CompanyDeleterCompanyBusinessUnitConnectorPersistenceFactory.php
  bundles/company-deleter-company-business-unit-connector/tests/FondOfOryx/.gitkeep
  bundles/company-deleter-company-business-unit-connector/tests/_bootstrap.php
  bundles/company-deleter-company-business-unit-connector/tests/_data/.gitkeep
  bundles/company-deleter-company-business-unit-connector/tests/_output/.gitignore
  bundles/company-deleter-company-business-unit-connector/tests/_support/.gitkeep
Labels: enhancement

#249 Company deleter erp delivery note connector
  bundles/company-deleter-erp-delivery-note-connector/.github/workflows/main.yml
  bundles/company-deleter-erp-delivery-note-connector/.gitignore
  bundles/company-deleter-erp-delivery-note-connector/LICENSE
  bundles/company-deleter-erp-delivery-note-connector/Makefile
  bundles/company-deleter-erp-delivery-note-connector/README.md
  bundles/company-deleter-erp-delivery-note-connector/codeception.yml
  bundles/company-deleter-erp-delivery-note-connector/composer.json
  bundles/company-deleter-erp-delivery-note-connector/phpstan.neon
  bundles/company-deleter-erp-delivery-note-connector/src/FondOfOryx/Zed/CompanyDeleterErpDeliveryNoteConnector/Business/CompanyDeleterErpDeliveryNoteConnectorBusinessFactory.php
  bundles/company-deleter-erp-delivery-note-connector/src/FondOfOryx/Zed/CompanyDeleterErpDeliveryNoteConnector/Business/CompanyDeleterErpDeliveryNoteConnectorFacade.php
  bundles/company-deleter-erp-delivery-note-connector/src/FondOfOryx/Zed/CompanyDeleterErpDeliveryNoteConnector/Business/CompanyDeleterErpDeliveryNoteConnectorFacadeInterface.php
  bundles/company-deleter-erp-delivery-note-connector/src/FondOfOryx/Zed/CompanyDeleterErpDeliveryNoteConnector/Business/Model/ErpDeliveryNoteDeleter.php
  bundles/company-deleter-erp-delivery-note-connector/src/FondOfOryx/Zed/CompanyDeleterErpDeliveryNoteConnector/Business/Model/ErpDeliveryNoteDeleterInterface.php
  bundles/company-deleter-erp-delivery-note-connector/src/FondOfOryx/Zed/CompanyDeleterErpDeliveryNoteConnector/Communication/Plugin/ErpDeliveryNoteDeleterPrePlugin.php
  bundles/company-deleter-erp-delivery-note-connector/src/FondOfOryx/Zed/CompanyDeleterErpDeliveryNoteConnector/Persistence/CompanyDeleterErpDeliveryNoteConnectorEntityManager.php
  bundles/company-deleter-erp-delivery-note-connector/src/FondOfOryx/Zed/CompanyDeleterErpDeliveryNoteConnector/Persistence/CompanyDeleterErpDeliveryNoteConnectorEntityManagerInterface.php
  bundles/company-deleter-erp-delivery-note-connector/src/FondOfOryx/Zed/CompanyDeleterErpDeliveryNoteConnector/Persistence/CompanyDeleterErpDeliveryNoteConnectorPersistenceFactory.php
  bundles/company-deleter-erp-delivery-note-connector/tests/FondOfOryx/.gitkeep
  bundles/company-deleter-erp-delivery-note-connector/tests/_bootstrap.php
  bundles/company-deleter-erp-delivery-note-connector/tests/_data/.gitkeep
  bundles/company-deleter-erp-delivery-note-connector/tests/_output/.gitignore
  bundles/company-deleter-erp-delivery-note-connector/tests/_support/.gitkeep
Labels: enhancement

#254 Company deleter unit tests
  bundles/company-deleter-company-business-unit-connector/tests/FondOfOryx/Zed/CompanyDeleterCompanyBusinessUnitConnector/Business/CompanyDeleterCompanyBusinessUnitConnectorBusinessFactoryTest.php
  bundles/company-deleter-company-business-unit-connector/tests/FondOfOryx/Zed/CompanyDeleterCompanyBusinessUnitConnector/Business/CompanyDeleterCompanyBusinessUnitConnectorFacadeTest.php
  bundles/company-deleter-company-business-unit-connector/tests/FondOfOryx/Zed/CompanyDeleterCompanyBusinessUnitConnector/Business/Model/BusinessUnitDeleterTest.php
  bundles/company-deleter-company-business-unit-connector/tests/FondOfOryx/Zed/CompanyDeleterCompanyBusinessUnitConnector/Communication/Plugin/CompanyBusinessUnitDeleterPrePluginTest.php
  bundles/company-deleter-company-role-connector/tests/FondOfOryx/Zed/CompanyDeleterCompanyRoleConnector/Business/CompanyDeleterCompanyRoleConnectorBusinessFactoryTest.php
  bundles/company-deleter-company-role-connector/tests/FondOfOryx/Zed/CompanyDeleterCompanyRoleConnector/Business/CompanyDeleterCompanyRoleConnectorFacadeTest.php
  bundles/company-deleter-company-role-connector/tests/FondOfOryx/Zed/CompanyDeleterCompanyRoleConnector/Business/Model/CompanyRoleDeleterTest.php
  bundles/company-deleter-company-role-connector/tests/FondOfOryx/Zed/CompanyDeleterCompanyRoleConnector/Communication/Plugin/CompanyRoleDeleterPrePluginTest.php
  bundles/company-deleter-company-user-connector/tests/FondOfOryx/Zed/CompanyDeleterCompanyUserConnector/Business/CompanyDeleterCompanyUserConnectorBusinessFactoryTest.php
  bundles/company-deleter-company-user-connector/tests/FondOfOryx/Zed/CompanyDeleterCompanyUserConnector/Business/CompanyDeleterCompanyUserConnectorFacadeTest.php
  bundles/company-deleter-company-user-connector/tests/FondOfOryx/Zed/CompanyDeleterCompanyUserConnector/Business/Model/CompanyUserDeleterTest.php
  bundles/company-deleter-company-user-connector/tests/FondOfOryx/Zed/CompanyDeleterCompanyUserConnector/Communication/Plugin/CompanyUserDeleterPrePluginTest.php
  bundles/company-deleter-erp-delivery-note-connector/tests/FondOfOryx/Zed/CompanyDeleterErpDeliveryNoteConnector/Business/CompanyDeleterErpDeliveryNoteConnectorBusinessFactoryTest.php
  bundles/company-deleter-erp-delivery-note-connector/tests/FondOfOryx/Zed/CompanyDeleterErpDeliveryNoteConnector/Business/CompanyDeleterErpDeliveryNoteConnectorFacadeTest.php
  bundles/company-deleter-erp-delivery-note-connector/tests/FondOfOryx/Zed/CompanyDeleterErpDeliveryNoteConnector/Business/Model/ErpDeliveryNoteDeleterTest.php
  bundles/company-deleter-erp-delivery-note-connector/tests/FondOfOryx/Zed/CompanyDeleterErpDeliveryNoteConnector/Communication/Plugin/ErpDeliveryNoteDeleterPrePluginTest.php
  bundles/company-deleter-erp-invoice-connector/tests/FondOfOryx/Zed/CompanyDeleterErpInvoiceConnector/Business/CompanyDeleterErpInvoiceConnectorBusinessFactoryTest.php
  bundles/company-deleter-erp-invoice-connector/tests/FondOfOryx/Zed/CompanyDeleterErpInvoiceConnector/Business/CompanyDeleterErpInvoiceConnectorFacadeTest.php
  bundles/company-deleter-erp-invoice-connector/tests/FondOfOryx/Zed/CompanyDeleterErpInvoiceConnector/Business/Model/ErpInvoiceDeleterTest.php
  bundles/company-deleter-erp-invoice-connector/tests/FondOfOryx/Zed/CompanyDeleterErpInvoiceConnector/Communication/Plugin/ErpInvoiceDeleterPrePluginTest.php
  bundles/company-deleter-erp-order-connector/tests/FondOfOryx/Zed/CompanyDeleterErpOrderConnector/Business/CompanyDeleterErpOrderConnectorBusinessFactoryTest.php
  bundles/company-deleter-erp-order-connector/tests/FondOfOryx/Zed/CompanyDeleterErpOrderConnector/Business/CompanyDeleterErpOrderConnectorFacadeTest.php
  bundles/company-deleter-erp-order-connector/tests/FondOfOryx/Zed/CompanyDeleterErpOrderConnector/Business/Model/ErpOrderDeleterTest.php
  bundles/company-deleter-erp-order-connector/tests/FondOfOryx/Zed/CompanyDeleterErpOrderConnector/Communication/Plugin/ErpOrderDeleterPrePluginTest.php
  bundles/company-deleter-product-list-connector/composer.json
  bundles/company-deleter-product-list-connector/tests/FondOfOryx/Zed/CompanyDeleterProductListConnector/Business/CompanyDeleterProductListConnectorBusinessFactoryTest.php
  bundles/company-deleter-product-list-connector/tests/FondOfOryx/Zed/CompanyDeleterProductListConnector/Business/CompanyDeleterProductListConnectorFacadeTest.php
  bundles/company-deleter-product-list-connector/tests/FondOfOryx/Zed/CompanyDeleterProductListConnector/Business/Model/CompanyToProductListDeleterTest.php
  bundles/company-deleter-product-list-connector/tests/FondOfOryx/Zed/CompanyDeleterProductListConnector/Communication/Plugin/CompanyToProductListDeleterPrePluginTest.php
  bundles/company-deleter/src/FondOfOryx/Zed/CompanyDeleter/Business/Executor/PluginExecutor.php
  bundles/company-deleter/tests/FondOfOryx/Zed/CompanyDeleter/Business/CompanyDeleterBusinessFactoryTest.php
  bundles/company-deleter/tests/FondOfOryx/Zed/CompanyDeleter/Business/CompanyDeleterFacadeTest.php
  bundles/company-deleter/tests/FondOfOryx/Zed/CompanyDeleter/Business/Executor/PluginExecutorTest.php
  bundles/company-deleter/tests/FondOfOryx/Zed/CompanyDeleter/Business/Model/CompanyDeleterTest.php
  bundles/company-deleter/tests/FondOfOryx/Zed/CompanyDeleter/Dependency/Facade/CompanyDeleterToCompanyFacadeBridgeTest.php
  codeception.yml
  composer.json
  dandelion.json
Labels: enhancement

#266 fix: allow api payload value to be false
  bundles/stock-product-api/src/FondOfOryx/Zed/StockProductApi/Business/Model/Validator/StockProductApiValidator.php
  dandelion.json
Labels: bug

#268 :sparkles: Feat: extend foo_erp_order table with is_canceled field
  bundles/erp-order/src/FondOfOryx/Zed/ErpOrder/Persistence/Propel/Schema/erp_order.schema.xml
Labels: enhancement

#267 :package: add initial stuff
  bundles/companies-rest-api/.github/workflows/main.yml
  bundles/companies-rest-api/.gitignore
  bundles/companies-rest-api/LICENSE
  bundles/companies-rest-api/Makefile
  bundles/companies-rest-api/codeception.yml
  bundles/companies-rest-api/composer.json
  bundles/companies-rest-api/phpstan.neon
  bundles/companies-rest-api/src/FondOfOryx/Client/CompaniesRestApi/CompaniesRestApiClientInterface.php
  bundles/companies-rest-api/src/FondOfOryx/Client/CompaniesRestApi/Dependency/Client/CompaniesRestApiToZedRequestClientInterface.php
  bundles/companies-rest-api/src/FondOfOryx/Client/CompaniesRestApi/Zed/CompaniesRestApiStubInterface.php
  bundles/companies-rest-api/src/FondOfOryx/Glue/CompaniesRestApi/Processor/Deleter/CompanyDeleterInterface.php
  bundles/companies-rest-api/src/FondOfOryx/Glue/CompaniesRestApi/Processor/Mapper/CompanyCollectionMapperInterface.php
  bundles/companies-rest-api/src/FondOfOryx/Shared/CompaniesRestApi/Transfer/companies_rest_api.transfer.xml
  bundles/companies-rest-api/tests/FondOfOryx/.gitkeep
  bundles/companies-rest-api/tests/_bootstrap.php
  bundles/companies-rest-api/tests/_data/.gitkeep
  bundles/companies-rest-api/tests/_output/.gitignore
  bundles/companies-rest-api/tests/_support/.gitkeep
  composer.json
Labels: enhancement

#274 Companies rest api permission
  bundles/companies-rest-api-permission/.editorconfig
  bundles/companies-rest-api-permission/.github/workflows/main.yml
  bundles/companies-rest-api-permission/.gitignore
  bundles/companies-rest-api-permission/LICENSE
  bundles/companies-rest-api-permission/Makefile
  bundles/companies-rest-api-permission/README.md
  bundles/companies-rest-api-permission/codeception.yml
  bundles/companies-rest-api-permission/composer.json
  bundles/companies-rest-api-permission/phpstan.neon
  bundles/companies-rest-api-permission/src/FondOfOryx/Client/CompaniesRestApiPermission/CompaniesRestApiPermissionClientInterface.php
  bundles/companies-rest-api-permission/src/FondOfOryx/Client/CompaniesRestApiPermission/Dependency/Client/CompaniesRestApiPermissionToZedRequestInterface.php
  bundles/companies-rest-api-permission/src/FondOfOryx/Client/CompaniesRestApiPermission/Zed/CompaniesRestApiPermissionStubInterface.php
  bundles/companies-rest-api-permission/src/FondOfOryx/Shared/CompaniesRestApiPermission/Transfer/companies_rest_api_permission.transfer.xml
  bundles/companies-rest-api-permission/src/FondOfOryx/Zed/CompaniesRestApiPermission/Persistence/CompaniesRestApiPermissionRepositoryInterface.php
  bundles/companies-rest-api-permission/tests/FondOfOryx/.gitkeep
  bundles/companies-rest-api-permission/tests/_bootstrap.php
  bundles/companies-rest-api-permission/tests/_data/.gitkeep
  bundles/companies-rest-api-permission/tests/_output/.gitignore
  bundles/companies-rest-api-permission/tests/_support/.gitkeep
  composer.json
Labels: enhancement

#275 :sparkles: add business logic to companies rest api permission
  bundles/companies-rest-api-permission/composer.json
  bundles/companies-rest-api-permission/src/FondOfOryx/Client/CompaniesRestApiPermission/CompaniesRestApiPermissionClient.php
  bundles/companies-rest-api-permission/src/FondOfOryx/Client/CompaniesRestApiPermission/CompaniesRestApiPermissionDependencyProvider.php
  bundles/companies-rest-api-permission/src/FondOfOryx/Client/CompaniesRestApiPermission/CompaniesRestApiPermissionFactory.php
  bundles/companies-rest-api-permission/src/FondOfOryx/Client/CompaniesRestApiPermission/Dependency/Client/CompaniesRestApiPermissionToZedRequestBridge.php
  bundles/companies-rest-api-permission/src/FondOfOryx/Client/CompaniesRestApiPermission/Zed/CompaniesRestApiPermissionStub.php
  bundles/companies-rest-api-permission/src/FondOfOryx/Zed/CompaniesRestApiPermission/Communication/Controller/GatewayController.php
  bundles/companies-rest-api-permission/src/FondOfOryx/Zed/CompaniesRestApiPermission/Communication/Plugin/Permission/CanDeleteCompanyPermissionPlugin.php
  bundles/companies-rest-api-permission/src/FondOfOryx/Zed/CompaniesRestApiPermission/Persistence/CompaniesRestApiPermissionPersistenceFactory.php
  bundles/companies-rest-api-permission/src/FondOfOryx/Zed/CompaniesRestApiPermission/Persistence/CompaniesRestApiPermissionRepository.php
Labels: enhancement

#278 🔖 release modules responsable for the canceled orders handling
  dandelion.json
Labels: enhancement

#280 🐛 add `isCanceled` value in the transfer object
  bundles/erp-order-page-search-rest-api/src/FondOfOryx/Shared/ErpOrderPageSearchRestApi/Transfer/erp_order_page_search_rest_api.transfer.xml
  dandelion.json
Labels: bug

#282 Erp delivery note tracking data es optimization
  bundles/erp-delivery-note-page-search-rest-api/src/FondOfOryx/Glue/ErpDeliveryNotePageSearchRestApi/Model/Mapper/RestErpDeliveryNotePageSearchCollectionResponseMapper.php
  bundles/erp-delivery-note-page-search-rest-api/src/FondOfOryx/Shared/ErpDeliveryNotePageSearchRestApi/ErpDeliveryNotePageSearchRestApiConstants.php
  bundles/erp-delivery-note-page-search-rest-api/tests/FondOfOryx/Glue/ErpDeliveryNotePageSearchRestApi/Model/Mapper/RestErpDeliveryNotePageSearchCollectionResponseMapperTest.php
  bundles/erp-delivery-note-page-search/src/FondOfOryx/Zed/ErpDeliveryNotePageSearch/Business/Publisher/ErpDeliveryNotePageSearchPublisher.php
  dandelion.json
Labels: bug

#284 :package: Companies rest api permissions
  bundles/companies-rest-api-permission/composer.json
  bundles/companies-rest-api-permission/data/translation/Zed/de_DE.csv
  bundles/companies-rest-api-permission/data/translation/Zed/en_US.csv
  bundles/companies-rest-api-permission/src/FondOfOryx/Client/CompaniesRestApiPermission/CompaniesRestApiPermissionClient.php
  bundles/companies-rest-api-permission/src/FondOfOryx/Client/CompaniesRestApiPermission/CompaniesRestApiPermissionClientInterface.php
  bundles/companies-rest-api-permission/src/FondOfOryx/Shared/CompaniesRestApiPermission/Transfer/companies_rest_api_permission.transfer.xml
  bundles/companies-rest-api-permission/src/FondOfOryx/Zed/CompaniesRestApiPermission/Communication/Controller/GatewayController.php
  bundles/companies-rest-api-permission/src/FondOfOryx/Zed/CompaniesRestApiPermission/Persistence/CompaniesRestApiPermissionRepository.php
  bundles/companies-rest-api-permission/src/FondOfOryx/Zed/CompaniesRestApiPermission/Persistence/CompaniesRestApiPermissionRepositoryInterface.php
  bundles/companies-rest-api-permission/src/FondOfOryx/Zed/CompaniesRestApiPermission/Persistence/Propel/Schema/spy_company.schema.xml
  dandelion.json
Labels: enhancement

#287 ✨ Add zed contracts to `business-on-behalf-rest-api`-bundle
  bundles/business-on-behalf-rest-api/src/FondOfOryx/Shared/BusinessOnBehalfRestApi/Transfer/business_on_behalf_rest_api.transfer.xml
  bundles/business-on-behalf-rest-api/src/FondOfOryx/Zed/BusinessOnBehalfRestApi/Business/BusinessOnBehalfRestApiFacadeInterface.php
  bundles/business-on-behalf-rest-api/src/FondOfOryx/Zed/BusinessOnBehalfRestApi/Business/Reader/CompanyUserReaderInterface.php
  bundles/business-on-behalf-rest-api/src/FondOfOryx/Zed/BusinessOnBehalfRestApi/Business/Writer/CompanyUserWriterInterface.php
  bundles/business-on-behalf-rest-api/src/FondOfOryx/Zed/BusinessOnBehalfRestApi/Dependency/Facade/BusinessOnBehalfRestApiToBusinessOnBehalfFacadeInterface.php
  bundles/business-on-behalf-rest-api/src/FondOfOryx/Zed/BusinessOnBehalfRestApi/Dependency/Facade/BusinessOnBehalfRestApiToCompanyUserFacadeInterface.php
  bundles/business-on-behalf-rest-api/src/FondOfOryx/Zed/BusinessOnBehalfRestApi/Persistence/BusinessOnBehalfRestApiRepositoryInterface.php
  codeception.yml
  composer.json
Labels: enhancement

#289 ✨ Add client layer to `business-on-behalf-rest-api`-bundle
  bundles/business-on-behalf-rest-api/src/FondOfOryx/Client/BusinessOnBehalfRestApi/BusinessOnBehalfRestApiClient.php
  bundles/business-on-behalf-rest-api/src/FondOfOryx/Client/BusinessOnBehalfRestApi/BusinessOnBehalfRestApiClientInterface.php
  bundles/business-on-behalf-rest-api/src/FondOfOryx/Client/BusinessOnBehalfRestApi/BusinessOnBehalfRestApiDependencyProvider.php
  bundles/business-on-behalf-rest-api/src/FondOfOryx/Client/BusinessOnBehalfRestApi/BusinessOnBehalfRestApiFactory.php
  bundles/business-on-behalf-rest-api/src/FondOfOryx/Client/BusinessOnBehalfRestApi/Dependency/Client/BusinessOnBehalfRestApiToZedRequestClientBridge.php
  bundles/business-on-behalf-rest-api/src/FondOfOryx/Client/BusinessOnBehalfRestApi/Dependency/Client/BusinessOnBehalfRestApiToZedRequestClientInterface.php
  bundles/business-on-behalf-rest-api/src/FondOfOryx/Client/BusinessOnBehalfRestApi/Zed/BusinessOnBehalfRestApiZedStub.php
  bundles/business-on-behalf-rest-api/src/FondOfOryx/Client/BusinessOnBehalfRestApi/Zed/BusinessOnBehalfRestApiZedStubInterface.php
  bundles/business-on-behalf-rest-api/tests/FondOfOryx/Client/BusinessOnBehalfRestApi/BusinessOnBehalfRestApiClientTest.php
  bundles/business-on-behalf-rest-api/tests/FondOfOryx/Client/BusinessOnBehalfRestApi/BusinessOnBehalfRestApiDependencyProviderTest.php
  bundles/business-on-behalf-rest-api/tests/FondOfOryx/Client/BusinessOnBehalfRestApi/BusinessOnBehalfRestApiFactoryTest.php
  bundles/business-on-behalf-rest-api/tests/FondOfOryx/Client/BusinessOnBehalfRestApi/Dependency/Client/BusinessOnBehalfRestApiToZedRequestClientBridgeTest.php
  bundles/business-on-behalf-rest-api/tests/FondOfOryx/Client/BusinessOnBehalfRestApi/Zed/BusinessOnBehalfRestApiZedStubTest.php
  composer.json
Labels: enhancement

#290 ✨ Add glue contracts to `business-on-behalf-rest-api`-bundle
  bundles/business-on-behalf-rest-api/src/FondOfOryx/Glue/BusinessOnBehalfRestApi/BusinessOnBehalfRestApiConfig.php
  bundles/business-on-behalf-rest-api/src/FondOfOryx/Glue/BusinessOnBehalfRestApi/Processor/Builder/RestResponseBuilderInterface.php
  bundles/business-on-behalf-rest-api/src/FondOfOryx/Glue/BusinessOnBehalfRestApi/Processor/BusinessOnBehalf/BusinessOnBehalfProcessorInterface.php
  bundles/business-on-behalf-rest-api/src/FondOfOryx/Glue/BusinessOnBehalfRestApi/Processor/Filter/IdCustomerFilterInterface.php
  bundles/business-on-behalf-rest-api/src/FondOfOryx/Glue/BusinessOnBehalfRestApi/Processor/Mapper/RestBusinessOnBehalfRequestMapperInterface.php
  composer.json
Labels: enhancement

#291 ✨ Make `companies-rest-api-permission`-bundle releasable
  bundles/companies-rest-api-permission/tests/FondOfOryx/Client/CompaniesRestApiPermission/CompaniesRestApiPermissionClientTest.php
  bundles/companies-rest-api-permission/tests/FondOfOryx/Client/CompaniesRestApiPermission/CompaniesRestApiPermissionFactoryTest.php
  bundles/companies-rest-api-permission/tests/FondOfOryx/Client/CompaniesRestApiPermission/Dependency/Client/CompaniesRestApiPermissionToZedRequestClientBridgeTest.php
  bundles/companies-rest-api-permission/tests/FondOfOryx/Client/CompaniesRestApiPermission/Zed/CompaniesRestApiPermissionStubTest.php
  bundles/companies-rest-api-permission/tests/FondOfOryx/Zed/CompaniesRestApiPermission/Communication/Controller/GatewayControllerTest.php
  codeception.yml
  dandelion.json
Labels: enhancement

#292 :sparkles: make company-rest-api bundle releaseable
  bundles/companies-rest-api/src/FondOfOryx/Zed/CompaniesRestApi/Business/Deleter/CompanyDeleter.php
  bundles/companies-rest-api/tests/FondOfOryx/Client/CompaniesRestApi/CompaniesRestApiClientTest.php
  bundles/companies-rest-api/tests/FondOfOryx/Client/CompaniesRestApi/CompaniesRestApiFactoryTest.php
  bundles/companies-rest-api/tests/FondOfOryx/Client/CompaniesRestApi/Dependency/Client/CompaniesRestApiToZedRequestClientBridgeTest.php
  bundles/companies-rest-api/tests/FondOfOryx/Client/CompaniesRestApi/Zed/CompaniesRestApiStubTest.php
  bundles/companies-rest-api/tests/FondOfOryx/Glue/CompaniesRestApi/CompaniesRestApiFactoryTest.php
  bundles/companies-rest-api/tests/FondOfOryx/Glue/CompaniesRestApi/Controller/CompaniesResourceControllerTest.php
  bundles/companies-rest-api/tests/FondOfOryx/Glue/CompaniesRestApi/Dependency/Client/CompaniesRestApiToCompaniesRestApiPermissionBridgeTest.php
  bundles/companies-rest-api/tests/FondOfOryx/Glue/CompaniesRestApi/Plugin/GlueApplicationExtension/CompaniesRestApiResourceRoutePluginTest.php
  bundles/companies-rest-api/tests/FondOfOryx/Glue/CompaniesRestApi/Processor/Builder/RestResponseBuilderTest.php
  bundles/companies-rest-api/tests/FondOfOryx/Glue/CompaniesRestApi/Processor/Deleter/CompanyDeleterTest.php
  bundles/companies-rest-api/tests/FondOfOryx/Glue/CompaniesRestApi/Processor/Mapper/CompanyMapperTest.php
  bundles/companies-rest-api/tests/FondOfOryx/Glue/CompaniesRestApi/Processor/Mapper/PermissionRequestMapperTest.php
  bundles/companies-rest-api/tests/FondOfOryx/Glue/CompaniesRestApi/Processor/Permission/PermissionCheckerTest.php
  bundles/companies-rest-api/tests/FondOfOryx/Zed/CompaniesRestApi/Business/CompaniesRestApiBusinessFactoryTest.php
  bundles/companies-rest-api/tests/FondOfOryx/Zed/CompaniesRestApi/Business/CompaniesRestApiFacadeTest.php
  bundles/companies-rest-api/tests/FondOfOryx/Zed/CompaniesRestApi/Business/Deleter/CompanyDeleterTest.php
  bundles/companies-rest-api/tests/FondOfOryx/Zed/CompaniesRestApi/Communication/Controller/GatewayControllerTest.php
  bundles/companies-rest-api/tests/FondOfOryx/Zed/CompaniesRestApi/Dependency/Facade/CompaniesRestApiToCompanyDeleterFacadeBridgeTest.php
  codeception.yml
  dandelion.json
Labels: enhancement

#293 ✨ Implement glue contracts to `business-on-behalf-rest-api`-bundle
  bundles/business-on-behalf-rest-api/src/FondOfOryx/Glue/BusinessOnBehalfRestApi/BusinessOnBehalfRestApiFactory.php
  bundles/business-on-behalf-rest-api/src/FondOfOryx/Glue/BusinessOnBehalfRestApi/Controller/BusinessOnBehalfResourceController.php
  bundles/business-on-behalf-rest-api/src/FondOfOryx/Glue/BusinessOnBehalfRestApi/Plugin/GlueApplicationExtension/BusinessOnBehalfResourceRoutePlugin.php
  bundles/business-on-behalf-rest-api/src/FondOfOryx/Glue/BusinessOnBehalfRestApi/Processor/Builder/RestResponseBuilder.php
  bundles/business-on-behalf-rest-api/src/FondOfOryx/Glue/BusinessOnBehalfRestApi/Processor/Builder/RestResponseBuilderInterface.php
  bundles/business-on-behalf-rest-api/src/FondOfOryx/Glue/BusinessOnBehalfRestApi/Processor/BusinessOnBehalf/BusinessOnBehalfProcessor.php
  bundles/business-on-behalf-rest-api/src/FondOfOryx/Glue/BusinessOnBehalfRestApi/Processor/Filter/IdCustomerFilter.php
  bundles/business-on-behalf-rest-api/src/FondOfOryx/Glue/BusinessOnBehalfRestApi/Processor/Mapper/RestBusinessOnBehalfRequestMapper.php
  bundles/business-on-behalf-rest-api/tests/FondOfOryx/Glue/BusinessOnBehalfRestApi/BusinessOnBehalfRestApiFactoryTest.php
  bundles/business-on-behalf-rest-api/tests/FondOfOryx/Glue/BusinessOnBehalfRestApi/Controller/BusinessOnBehalfResourceControllerTest.php
  bundles/business-on-behalf-rest-api/tests/FondOfOryx/Glue/BusinessOnBehalfRestApi/Plugin/GlueApplicationExtension/BusinessOnBehalfResourceRoutePluginTest.php
  bundles/business-on-behalf-rest-api/tests/FondOfOryx/Glue/BusinessOnBehalfRestApi/Processor/Builder/RestResponseBuilderTest.php
  bundles/business-on-behalf-rest-api/tests/FondOfOryx/Glue/BusinessOnBehalfRestApi/Processor/BusinessOnBehalf/BusinessOnBehalfProcessorTest.php
  bundles/business-on-behalf-rest-api/tests/FondOfOryx/Glue/BusinessOnBehalfRestApi/Processor/Filter/IdCustomerFilterTest.php
  bundles/business-on-behalf-rest-api/tests/FondOfOryx/Glue/BusinessOnBehalfRestApi/Processor/Mapper/RestBusinessOnBehalfRequestMapperTest.php
Labels: enhancement

#294 ✨ Add package ecosystem `github-actions` to dependabot
  .github/dependabot.yml
Labels: enhancement

#297 ✨ Initialize `business-on-behalf-product-list-connector`-bundle
  bundles/business-on-behalf-product-list-connector/.github/workflows/main.yml
  bundles/business-on-behalf-product-list-connector/LICENSE
  bundles/business-on-behalf-product-list-connector/Makefile
  bundles/business-on-behalf-product-list-connector/codeception.yml
  bundles/business-on-behalf-product-list-connector/composer.json
  bundles/business-on-behalf-product-list-connector/phpstan.neon
  bundles/business-on-behalf-product-list-connector/tests/_bootstrap.php
  bundles/business-on-behalf-product-list-connector/tests/_data/.gitkeep
  bundles/business-on-behalf-product-list-connector/tests/_output/.gitkeep
  bundles/business-on-behalf-product-list-connector/tests/_support/.gitkeep
  codeception.yml
  composer.json
Labels: enhancement

#298 ✨ Add contracts to `business-on-behalf-product-list-connector`-bundle
  bundles/business-on-behalf-product-list-connector/src/FondOfOryx/Shared/BusinessOnBehalfProductListConnector/Transfer/business_on_behalf_product_list_connector.transfer.xml
  bundles/business-on-behalf-product-list-connector/src/FondOfOryx/Zed/BusinessOnBehalfProductListConnector/Business/BusinessOnBehalfProductListConnectorFacadeInterface.php
  bundles/business-on-behalf-product-list-connector/src/FondOfOryx/Zed/BusinessOnBehalfProductListConnector/Business/Expander/QuoteExpanderInterface.php
  bundles/business-on-behalf-product-list-connector/src/FondOfOryx/Zed/BusinessOnBehalfProductListConnector/Business/Filter/RestrictedItemsFilterInterface.php
  bundles/business-on-behalf-product-list-connector/src/FondOfOryx/Zed/BusinessOnBehalfProductListConnector/Business/Reader/CompanyUserReaderInterface.php
  bundles/business-on-behalf-product-list-connector/src/FondOfOryx/Zed/BusinessOnBehalfProductListConnector/Business/Reader/CustomerReaderInterface.php
  bundles/business-on-behalf-product-list-connector/src/FondOfOryx/Zed/BusinessOnBehalfProductListConnector/Business/Validator/ProductListRestrictionValidatorInterface.php
  bundles/business-on-behalf-product-list-connector/src/FondOfOryx/Zed/BusinessOnBehalfProductListConnector/Business/Writer/CompanyUserWriterInterface.php
  bundles/business-on-behalf-product-list-connector/src/FondOfOryx/Zed/BusinessOnBehalfProductListConnector/Dependency/Facade/BusinessOnBehalfProductListConnectorToBusinessOnBehalfFacadeInterface.php
  bundles/business-on-behalf-product-list-connector/src/FondOfOryx/Zed/BusinessOnBehalfProductListConnector/Dependency/Facade/BusinessOnBehalfProductListConnectorToCustomerFacadeInterface.php
  bundles/business-on-behalf-product-list-connector/src/FondOfOryx/Zed/BusinessOnBehalfProductListConnector/Dependency/Facade/BusinessOnBehalfProductListConnectorToProductListFacadeInterface.php
  bundles/business-on-behalf-product-list-connector/src/FondOfOryx/Zed/BusinessOnBehalfProductListConnector/Persistence/BusinessOnBehalfProductListConnectorRepositoryInterface.php
Labels: enhancement

#299 ✨ Implement contracts of `business-on-behalf-product-list-connector`-bundle
  bundles/business-on-behalf-product-list-connector/src/FondOfOryx/Zed/BusinessOnBehalfProductListConnector/Business/BusinessOnBehalfProductListConnectorBusinessFactory.php
  bundles/business-on-behalf-product-list-connector/src/FondOfOryx/Zed/BusinessOnBehalfProductListConnector/Business/BusinessOnBehalfProductListConnectorFacade.php
  bundles/business-on-behalf-product-list-connector/src/FondOfOryx/Zed/BusinessOnBehalfProductListConnector/Business/Expander/QuoteExpander.php
  bundles/business-on-behalf-product-list-connector/src/FondOfOryx/Zed/BusinessOnBehalfProductListConnector/Business/Filter/RestrictedItemsFilter.php
  bundles/business-on-behalf-product-list-connector/src/FondOfOryx/Zed/BusinessOnBehalfProductListConnector/Business/Reader/CompanyUserReader.php
  bundles/business-on-behalf-product-list-connector/src/FondOfOryx/Zed/BusinessOnBehalfProductListConnector/Business/Reader/CustomerReader.php
  bundles/business-on-behalf-product-list-connector/src/FondOfOryx/Zed/BusinessOnBehalfProductListConnector/Business/Validator/ProductListRestrictionValidator.php
  bundles/business-on-behalf-product-list-connector/src/FondOfOryx/Zed/BusinessOnBehalfProductListConnector/Business/Writer/CompanyUserWriter.php
  bundles/business-on-behalf-product-list-connector/src/FondOfOryx/Zed/BusinessOnBehalfProductListConnector/BusinessOnBehalfProductListConnectorDependencyProvider.php
  bundles/business-on-behalf-product-list-connector/src/FondOfOryx/Zed/BusinessOnBehalfProductListConnector/Communication/Plugin/CartExtension/ProductListRestrictedItemsPreCheckPlugin.php
  bundles/business-on-behalf-product-list-connector/src/FondOfOryx/Zed/BusinessOnBehalfProductListConnector/Communication/Plugin/CartExtension/RemoveRestrictedItemsPreReloadPlugin.php
  bundles/business-on-behalf-product-list-connector/src/FondOfOryx/Zed/BusinessOnBehalfProductListConnector/Dependency/Facade/BusinessOnBehalfProductListConnectorToBusinessOnBehalfFacadeBridge.php
  bundles/business-on-behalf-product-list-connector/src/FondOfOryx/Zed/BusinessOnBehalfProductListConnector/Dependency/Facade/BusinessOnBehalfProductListConnectorToCustomerFacadeBridge.php
  bundles/business-on-behalf-product-list-connector/src/FondOfOryx/Zed/BusinessOnBehalfProductListConnector/Dependency/Facade/BusinessOnBehalfProductListConnectorToProductListFacadeBridge.php
  bundles/business-on-behalf-product-list-connector/src/FondOfOryx/Zed/BusinessOnBehalfProductListConnector/Persistence/BusinessOnBehalfProductListConnectorPersistenceFactory.php
  bundles/business-on-behalf-product-list-connector/src/FondOfOryx/Zed/BusinessOnBehalfProductListConnector/Persistence/BusinessOnBehalfProductListConnectorRepository.php
Labels: enhancement

#300 ✅ Add unit tests to `business-on-behalf-product-list-connector`-bundle
  bundles/business-on-behalf-product-list-connector/tests/FondOfOryx/Zed/BusinessOnBehalfProductListConnector/Business/BusinessOnBehalfProductListConnectorBusinessFactoryTest.php
  bundles/business-on-behalf-product-list-connector/tests/FondOfOryx/Zed/BusinessOnBehalfProductListConnector/Business/BusinessOnBehalfProductListConnectorFacadeTest.php
  bundles/business-on-behalf-product-list-connector/tests/FondOfOryx/Zed/BusinessOnBehalfProductListConnector/Business/Expander/QuoteExpanderTest.php
  bundles/business-on-behalf-product-list-connector/tests/FondOfOryx/Zed/BusinessOnBehalfProductListConnector/Business/Filter/RestrictedItemsFilterTest.php
  bundles/business-on-behalf-product-list-connector/tests/FondOfOryx/Zed/BusinessOnBehalfProductListConnector/Business/Reader/CompanyUserReaderTest.php
  bundles/business-on-behalf-product-list-connector/tests/FondOfOryx/Zed/BusinessOnBehalfProductListConnector/Business/Reader/CustomerReaderTest.php
  bundles/business-on-behalf-product-list-connector/tests/FondOfOryx/Zed/BusinessOnBehalfProductListConnector/Business/Validator/ProductListRestrictionValidatorTest.php
  bundles/business-on-behalf-product-list-connector/tests/FondOfOryx/Zed/BusinessOnBehalfProductListConnector/Business/Writer/CompanyUserWriterTest.php
  bundles/business-on-behalf-product-list-connector/tests/FondOfOryx/Zed/BusinessOnBehalfProductListConnector/BusinessOnBehalfProductListConnectorDependencyProviderTest.php
  bundles/business-on-behalf-product-list-connector/tests/FondOfOryx/Zed/BusinessOnBehalfProductListConnector/Communication/Plugin/CartExtension/ProductListRestrictedItemsPreCheckPluginTest.php
  bundles/business-on-behalf-product-list-connector/tests/FondOfOryx/Zed/BusinessOnBehalfProductListConnector/Communication/Plugin/CartExtension/RemoveRestrictedItemsPreReloadPluginTest.php
  bundles/business-on-behalf-product-list-connector/tests/FondOfOryx/Zed/BusinessOnBehalfProductListConnector/Dependency/Facade/BusinessOnBehalfProductListConnectorToBusinessOnBehalfFacadeBridgeTest.php
  bundles/business-on-behalf-product-list-connector/tests/FondOfOryx/Zed/BusinessOnBehalfProductListConnector/Dependency/Facade/BusinessOnBehalfProductListConnectorToCustomerFacadeBridgeTest.php
  bundles/business-on-behalf-product-list-connector/tests/FondOfOryx/Zed/BusinessOnBehalfProductListConnector/Dependency/Facade/BusinessOnBehalfProductListConnectorToProductListFacadeBridgeTest.php
Labels: enhancement

#301 🐛 Add bugfixes to `business-on-behalf-product-list-connector`
  bundles/business-on-behalf-product-list-connector/src/FondOfOryx/Zed/BusinessOnBehalfProductListConnector/Business/Reader/CustomerReader.php
  bundles/business-on-behalf-product-list-connector/src/FondOfOryx/Zed/BusinessOnBehalfProductListConnector/Dependency/Facade/BusinessOnBehalfProductListConnectorToCustomerFacadeBridge.php
  bundles/business-on-behalf-product-list-connector/src/FondOfOryx/Zed/BusinessOnBehalfProductListConnector/Dependency/Facade/BusinessOnBehalfProductListConnectorToCustomerFacadeInterface.php
  bundles/business-on-behalf-product-list-connector/src/FondOfOryx/Zed/BusinessOnBehalfProductListConnector/Persistence/BusinessOnBehalfProductListConnectorRepository.php
  bundles/business-on-behalf-product-list-connector/tests/FondOfOryx/Zed/BusinessOnBehalfProductListConnector/Business/Reader/CustomerReaderTest.php
  bundles/business-on-behalf-product-list-connector/tests/FondOfOryx/Zed/BusinessOnBehalfProductListConnector/Dependency/Facade/BusinessOnBehalfProductListConnectorToCustomerFacadeBridgeTest.php
Labels: bug
