Repository fond-of-oryx/fond-of-oryx, pull requests merged in 2023-11, with the labels that each got.

#458 🐛 Handle nullable locale
  bundles/company-user-mail-connector/composer.json
  bundles/company-user-mail-connector/src/FondOfOryx/Shared/CompanyUserMailConnector/Transfer/company_users_rest_api.transfer.xml
  bundles/company-user-mail-connector/src/FondOfOryx/Zed/CompanyUserMailConnector/Business/CompanyUserMailConnectorBusinessFactory.php
  bundles/company-user-mail-connector/src/FondOfOryx/Zed/CompanyUserMailConnector/Business/Model/Mail/CompanyUserCreationNotificationMailHandler.php
  bundles/company-user-mail-connector/src/FondOfOryx/Zed/CompanyUserMailConnector/Business/Model/Mail/MailHandler.php
  bundles/company-user-mail-connector/src/FondOfOryx/Zed/CompanyUserMailConnector/Business/Reader/LocaleReader.php
  bundles/company-user-mail-connector/src/FondOfOryx/Zed/CompanyUserMailConnector/Business/Reader/LocaleReaderInterface.php
  bundles/company-user-mail-connector/src/FondOfOryx/Zed/CompanyUserMailConnector/CompanyUserMailConnectorConfig.php
  bundles/company-user-mail-connector/src/FondOfOryx/Zed/CompanyUserMailConnector/CompanyUserMailConnectorDependencyProvider.php
  bundles/company-user-mail-connector/src/FondOfOryx/Zed/CompanyUserMailConnector/Dependency/Facade/CompanyUserMailConnectorToLocaleFacadeBridge.php
  bundles/company-user-mail-connector/src/FondOfOryx/Zed/CompanyUserMailConnector/Dependency/Facade/CompanyUserMailConnectorToLocaleFacadeInterface.php
  bundles/company-user-mail-connector/src/FondOfOryx/Zed/CompanyUserMailConnector/Persistence/CompanyUserMailConnectorPersistenceFactory.php
  bundles/company-user-mail-connector/src/FondOfOryx/Zed/CompanyUserMailConnector/Persistence/CompanyUserMailConnectorRepository.php
  bundles/company-user-mail-connector/tests/FondOfOryx/Zed/CompanyUserMailConnector/Business/CompanyUserMailConnectorBusinessFactoryTest.php
  bundles/company-user-mail-connector/tests/FondOfOryx/Zed/CompanyUserMailConnector/Business/Model/Mail/CompanyUserCreationNotificationMailHandlerTest.php
  bundles/company-user-mail-connector/tests/FondOfOryx/Zed/CompanyUserMailConnector/Business/Model/Mail/MailHandlerTest.php
  bundles/company-user-mail-connector/tests/FondOfOryx/Zed/CompanyUserMailConnector/Business/Reader/LocaleReaderTest.php
  bundles/company-user-mail-connector/tests/FondOfOryx/Zed/CompanyUserMailConnector/CompanyUserMailConnectorDependencyProviderTest.php
  bundles/company-user-mail-connector/tests/FondOfOryx/Zed/CompanyUserMailConnector/Dependency/CompanyUserMailConnectorToLocaleFacadeBridgeTest.php
  bundles/prepayment/src/FondOfOryx/Yves/Prepayment/Form/PrepaymentSubForm.php
  dandelion.json
Labels: bug

#459 🚀 Add caching to reduce locale sql queries
  bundles/company-user-mail-connector/src/FondOfOryx/Zed/CompanyUserMailConnector/Business/Reader/LocaleReader.php
  bundles/company-user-mail-connector/src/FondOfOryx/Zed/CompanyUserMailConnector/CompanyUserMailConnectorDependencyProvider.php
  bundles/company-user-mail-connector/tests/FondOfOryx/Zed/CompanyUserMailConnector/Business/Reader/LocaleReaderTest.php
Labels: enhancement

#460 🐛 Don't notify created company user
  bundles/company-user-mail-connector/src/FondOfOryx/Zed/CompanyUserMailConnector/Business/Model/Mail/CompanyUserCreationNotificationMailHandler.php
  bundles/company-user-mail-connector/tests/FondOfOryx/Zed/CompanyUserMailConnector/Business/Model/Mail/CompanyUserCreationNotificationMailHandlerTest.php
  dandelion.json
Labels: bug

#461 🧹 Remove `fond-of-spryker/country` from `fond-of-oryx/erp-order`
  bundles/erp-order/composer.json
  bundles/erp-order/src/FondOfOryx/Zed/ErpOrder/Dependency/Facade/ErpOrderToCountryFacadeBridge.php
  bundles/erp-order/src/FondOfOryx/Zed/ErpOrder/Dependency/Facade/ErpOrderToCountryFacadeInterface.php
  bundles/erp-order/src/FondOfOryx/Zed/ErpOrder/ErpOrderDependencyProvider.php
  bundles/erp-order/src/FondOfOryx/Zed/ErpOrder/Persistence/ErpOrderPersistenceFactory.php
  bundles/erp-order/src/FondOfOryx/Zed/ErpOrder/Persistence/Propel/Mapper/EntityToTransferMapper.php
  bundles/erp-order/tests/FondOfOryx/Zed/ErpOrder/Dependency/Facade/ErpOrderToCountryFacadeBridgeTest.php
Labels: dependencies

#462 🧹 Remove `fond-of-spryker/country` from `fond-of-oryx/erp-invoice`
  bundles/erp-invoice/composer.json
  bundles/erp-invoice/src/FondOfOryx/Zed/ErpInvoice/Dependency/Facade/ErpInvoiceToCountryFacadeBridge.php
  bundles/erp-invoice/src/FondOfOryx/Zed/ErpInvoice/Dependency/Facade/ErpInvoiceToCountryFacadeInterface.php
  bundles/erp-invoice/src/FondOfOryx/Zed/ErpInvoice/ErpInvoiceDependencyProvider.php
  bundles/erp-invoice/src/FondOfOryx/Zed/ErpInvoice/Persistence/ErpInvoicePersistenceFactory.php
  bundles/erp-invoice/src/FondOfOryx/Zed/ErpInvoice/Persistence/Propel/Mapper/EntityToTransferMapper.php
  bundles/erp-invoice/tests/FondOfOryx/Zed/ErpInvoice/Dependency/Facade/ErpInvoiceToCountryFacadeBridgeTest.php
Labels: dependencies

#463 🧹 Remove `fond-of-spryker/country` from `fond-of-oryx/erp-delivery-note`
  bundles/erp-delivery-note/composer.json
  bundles/erp-delivery-note/src/FondOfOryx/Zed/ErpDeliveryNote/Dependency/Facade/ErpDeliveryNoteToCountryFacadeBridge.php
  bundles/erp-delivery-note/src/FondOfOryx/Zed/ErpDeliveryNote/Dependency/Facade/ErpDeliveryNoteToCountryFacadeInterface.php
  bundles/erp-delivery-note/src/FondOfOryx/Zed/ErpDeliveryNote/ErpDeliveryNoteDependencyProvider.php
  bundles/erp-delivery-note/src/FondOfOryx/Zed/ErpDeliveryNote/Persistence/ErpDeliveryNotePersistenceFactory.php
  bundles/erp-delivery-note/src/FondOfOryx/Zed/ErpDeliveryNote/Persistence/Propel/Mapper/EntityToTransferMapper.php
  bundles/erp-delivery-note/tests/FondOfOryx/Zed/ErpDeliveryNote/Dependency/Facade/ErpDeliveryNoteToCountryFacadeBridgeTest.php
Labels: dependencies

#464 🧹 Remove `fond-of-spryker/country` from monorepo
  composer.json
Labels: dependencies

#465 🧹 Update `spryker/country` in all bundles
  bundles/country-oms-mail-connector/composer.json
  bundles/shipment-table-rate/composer.json
  bundles/tax-calculation-connector/composer.json
Labels: dependencies

#466 ✨ Release bundles that effected by removing `fond-of-spryker/country`
  dandelion.json
Labels: dependencies

#416 ✨ migrate make file generate-composer-sections
  Makefile
  Makefile.d/composer.sh
Labels: enhancement

#467 ✨ Release bundles that effected by updating `spryker/locale`
  dandelion.json
Labels: dependencies

#468 ✨ use `deleteCompanyUser` method instead `delete`
  bundles/company-user-api/src/FondOfOryx/Zed/CompanyUserApi/Business/Model/CompanyUserApi.php
  bundles/company-user-api/src/FondOfOryx/Zed/CompanyUserApi/Dependency/Facade/CompanyUserApiToCompanyUserFacadeBridge.php
  bundles/company-user-api/src/FondOfOryx/Zed/CompanyUserApi/Dependency/Facade/CompanyUserApiToCompanyUserFacadeInterface.php
  bundles/company-user-api/tests/FondOfOryx/Zed/CompanyUserApi/Business/Model/CompanyUserApiTest.php
  bundles/company-user-api/tests/FondOfOryx/Zed/CompanyUserApi/Dependency/Facade/CompanyUserApiToCompanyUserFacadeBridgeTest.php
Labels: enhancement

#472 🔖 update `bundle/company-user-api` version on 3.1.0
  dandelion.json
Labels: enhancement

#473 ✨ Initialize `customer-quote-connector`-bundle
  Makefile
  bundles/customer-quote-connector/.github/workflows/main.yml
  bundles/customer-quote-connector/LICENSE
  bundles/customer-quote-connector/Makefile
  bundles/customer-quote-connector/codeception.yml
  bundles/customer-quote-connector/composer.json
  bundles/customer-quote-connector/phpstan.neon
  bundles/customer-quote-connector/tests/_bootstrap.php
  bundles/customer-quote-connector/tests/_data/.gitkeep
  bundles/customer-quote-connector/tests/_output/.gitignore
  bundles/customer-quote-connector/tests/_support/.gitkeep
  codeception.yml
  composer.json
Labels: enhancement

#474 ✨ Implement `customer-quote-connector`-bundle
  bundles/customer-quote-connector/src/FondOfOryx/Shared/CustomerQuoteConnector/Transfer/customer_quote_connector.transfer.xml
  bundles/customer-quote-connector/src/FondOfOryx/Zed/CustomerQuoteConnector/Communication/CustomerQuoteConnectorCommunicationFactory.php
  bundles/customer-quote-connector/src/FondOfOryx/Zed/CustomerQuoteConnector/Communication/Plugin/QuoteExtension/CustomerQuoteExpanderPlugin.php
  bundles/customer-quote-connector/src/FondOfOryx/Zed/CustomerQuoteConnector/CustomerQuoteConnectorDependencyProvider.php
  bundles/customer-quote-connector/src/FondOfOryx/Zed/CustomerQuoteConnector/Dependency/Facade/CustomerQuoteConnectorToCustomerFacadeBridge.php
  bundles/customer-quote-connector/src/FondOfOryx/Zed/CustomerQuoteConnector/Dependency/Facade/CustomerQuoteConnectorToCustomerFacadeInterface.php
  bundles/customer-quote-connector/src/FondOfOryx/Zed/CustomerQuoteConnector/Persistence/CustomerQuoteConnectorPersistenceFactory.php
  bundles/customer-quote-connector/src/FondOfOryx/Zed/CustomerQuoteConnector/Persistence/CustomerQuoteConnectorRepository.php
  bundles/customer-quote-connector/src/FondOfOryx/Zed/CustomerQuoteConnector/Persistence/CustomerQuoteConnectorRepositoryInterface.php
  bundles/customer-quote-connector/tests/FondOfOryx/Zed/CustomerQuoteConnector/Communication/Plugin/QuoteExtension/CustomerQuoteExpanderPluginTest.php
  bundles/customer-quote-connector/tests/FondOfOryx/Zed/CustomerQuoteConnector/Dependency/Facade/CustomerQuoteConnectorToCustomerFacadeBridgeTest.php
  dandelion.json
Labels: enhancement

#475 🐛 Use correct container key
  bundles/customer-quote-connector/src/FondOfOryx/Zed/CustomerQuoteConnector/CustomerQuoteConnectorDependencyProvider.php
Labels: bug

#476 🐛 fix missing required `CompanyUserTransfer` parameters in `CompanyUserPreDeletePlugins`
  bundles/company-user-api/src/FondOfOryx/Zed/CompanyUserApi/Business/Model/CompanyUserApi.php
  bundles/company-user-api/tests/FondOfOryx/Zed/CompanyUserApi/Business/Model/CompanyUserApiTest.php
  dandelion.json
Labels: bug
